declare const _default: {
    affirmative: RegExp;
    alphaNumeric: RegExp;
    caPostalCode: RegExp;
    creditCard: RegExp;
    dateString: RegExp;
    email: RegExp;
    eppPhone: RegExp;
    hexadecimal: RegExp;
    hexColor: RegExp;
    ipv4: RegExp;
    ipv6: RegExp;
    nanpPhone: RegExp;
    socialSecurityNumber: RegExp;
    timeString: RegExp;
    ukPostCode: RegExp;
    url: RegExp;
    usZipCode: RegExp;
    dateStr: RegExp;
};
export default _default;
